name = "BrothersInArms Mods"
prefix = "bia"
author = "BrothersInArms"
files = [
    "LICENSE",
    "mod.cpp",
    "README.md",
    "BrothersInArms_mods_x64.dll",
]

exclude = ["*.psd", "*.png", "*.tga"]

modname = "BrothersInArms_mods"
key_name = "BrothersInArms_mods_{{version}}"
authority = "BrothersInArms_mods_{{version}}"

releasebuild = [
    "!set_version",
    "@zip",
    "!publish"
]

[header_exts]
version = "{{git \"id 8\"}}"

[scripts.extension]
    show_output = true
    steps_windows = [
        "cd extension && cargo build --release",
        "copy extension\\target\\release\\BrothersInArms_mods.dll BrothersInArms_mods_x64.dll"
    ]
    steps_linux = [
        "echo \"Unable to build extension on Linux\""
    ]

[scripts.set_version]
    steps_windows = [
        "powershell ./tools/Set-Version.ps1 {{version}} '@BrothersInArms_mods'"
    ]
    steps_linux = [
        "sed -i 's/0.0.0/{{version}}/' ./releases/{{version}}/@BrothersInArms_mods/mod.cpp"
    ]
    # show_output = true

[scripts.publish]
    steps_windows = [
        "powershell ./tools/Publish.ps1 {{version}} 1934142795 '@BrothersInArms_mods'"
    ]
    show_output = true
