name = "Brothers in Arms Mods"
prefix = "bia"
author = "Brothers in Arms"
files = [
    "LICENSE",
    "mod.cpp",
    "README.md",

]

exclude = ["*.psd", "*.png", "*.tga"]

modname = "brothersinarms_mods"
key_name = "brothersinarms_mods_{{version}}"
authority = "brothersinarms_mods_{{version}}"

releasebuild = [
    "!set_version",
    "@zip",
    "!publish"
]

[header_exts]
version = "{{git \"id 8\"}}"

[scripts.extension]
    show_output = true
    steps_windows = [
        "cd extension && cargo build --release",
        "copy extension\\target\\release\\brothersinarms_mods.dll brothersinarms_mods_x64.dll"
    ]
    steps_linux = [
        "echo \"Unable to build extension on Linux\""
    ]

[scripts.set_version]
    steps_windows = [
        "powershell ./tools/Set-Version.ps1 {{version}} '@brothersinarms_mods'"
    ]
    steps_linux = [
        "sed -i 's/0.0.0/{{version}}/' ./releases/{{version}}/@brothersinarms_mods/mod.cpp"
    ]
    # show_output = true

[scripts.publish]
    steps_windows = [
        "powershell ./tools/Publish.ps1 {{version}} 1934142795 '@brothersinarms_mods'"
    ]
    show_output = true
