name = "Brothers in Arms Mods - 0.0.0";
dir = "@Bbrotherinarms_mods";
author = "Brothers in Arms";
url = "https://github.com/dedos33/mods/";
logo = "\z\bia\addons\main\ui\logo_sm_ca.paa";
logoOver = "\z\bia\addons\main\ui\logo_sm_ca.paa";
overviewPicture = "\z\bia\addons\main\ui\logo_sm_ca.paa";
tooltip = "Brothers in Arms Mods";
description = "Brothers in Arms mods developed by Arma Forces community members.";
